#! /usr/bin/python3
from __future__ import print_function

from unicodedata import name
import sys
import argparse

import text_utils as tu


if __name__ == '__main__':

    p = argparse.ArgumentParser("Extract the name of the emojis from stdin and printed it separated by commas")
    p.add_argument('-k', '--keep', action='store_true', default=False, help='Keep the original text')
    args = p.parse_args()

    for line in sys.stdin:
        text = line
        emojis = tu.get_all_emojis(text)

        if args.keep:
            print('{}: {}'.format(','.join({name(e, '-') for e in emojis}), text))
        else:
            print('{}'.format(','.join({name(e, '-') for e in emojis}), text))


